name: eslint

on: push

jobs:
    eslint:
        
        name: ESLint
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./lifescape

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Run ESLint
              run: npm run lint